// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YellowphaseWebsite.Data;

#nullable disable

namespace YellowphaseWebsite.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260606170452_removeseller")]
    partial class removeseller
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("YellowphaseWebsite.Models.AppSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("YellowphaseWebsite.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("BusinessName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("YellowphaseWebsite.Models.ContactLead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ContactLeads");
                });

            modelBuilder.Entity("YellowphaseWebsite.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("YellowphaseWebsite.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUserSubmitted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProductType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SellerId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("SellerId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Solar",
                            CreatedAt = new DateTime(2026, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "High efficiency mono-crystalline solar panel.",
                            ImageUrl = "/images/products/solar1.webp",
                            IsApproved = true,
                            IsUserSubmitted = false,
                            Name = "Solar Panel 550W",
                            Price = 3200m,
                            ProductCode = "SOLAR-550W",
                            ProductType = "Product",
                            Quantity = 0
                        },
                        new
                        {
                            Id = 2,
                            Category = "Solar",
                            CreatedAt = new DateTime(2026, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Hybrid inverter for solar systems.",
                            ImageUrl = "/images/products/inverter1.png",
                            IsApproved = true,
                            IsUserSubmitted = false,
                            Name = "Hybrid Inverter 8kW",
                            Price = 18500m,
                            ProductCode = "INVERTER-8KW",
                            ProductType = "Product",
                            Quantity = 0
                        },
                        new
                        {
                            Id = 3,
                            Category = "Solar",
                            CreatedAt = new DateTime(2026, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Energy storage battery system.",
                            ImageUrl = "/images/products/battery1.png",
                            IsApproved = true,
                            IsUserSubmitted = false,
                            Name = "Lithium Battery 10kWh",
                            Price = 45000m,
                            ProductCode = "BATTERY-10KWH",
                            ProductType = "Product",
                            Quantity = 0
                        },
                        new
                        {
                            Id = 4,
                            Category = "Electrical",
                            CreatedAt = new DateTime(2026, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "DB Box",
                            ImageUrl = "/images/products/db1.webp",
                            IsApproved = true,
                            IsUserSubmitted = false,
                            Name = "Distribution Board",
                            Price = 1200m,
                            ProductCode = "DB-BOARD",
                            ProductType = "Product",
                            Quantity = 0
                        },
                        new
                        {
                            Id = 5,
                            Category = "Electrical",
                            CreatedAt = new DateTime(2026, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Copper cable",
                            ImageUrl = "/images/products/cable1.jpg",
                            IsApproved = true,
                            IsUserSubmitted = false,
                            Name = "Electrical Cable 2.5mm",
                            Price = 35m,
                            ProductCode = "CABLE-2.5",
                            ProductType = "Product",
                            Quantity = 0
                        },
                        new
                        {
                            Id = 6,
                            Category = "Electrical",
                            CreatedAt = new DateTime(2026, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Outdoor lighting",
                            ImageUrl = "/images/products/light1.jpg",
                            IsApproved = true,
                            IsUserSubmitted = false,
                            Name = "LED Flood Light 200W",
                            Price = 950m,
                            ProductCode = "LED-200W",
                            ProductType = "Product",
                            Quantity = 0
                        },
                        new
                        {
                            Id = 7,
                            Category = "ICT",
                            CreatedAt = new DateTime(2026, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Security system",
                            ImageUrl = "/images/products/cctv1.webp",
                            IsApproved = true,
                            IsUserSubmitted = false,
                            Name = "CCTV Camera Kit",
                            Price = 6200m,
                            ProductCode = "CCTV-KIT",
                            ProductType = "Product",
                            Quantity = 0
                        },
                        new
                        {
                            Id = 8,
                            Category = "Mechanical",
                            CreatedAt = new DateTime(2026, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Water pump",
                            ImageUrl = "/images/products/pump1.jpg",
                            IsApproved = true,
                            IsUserSubmitted = false,
                            Name = "Water Pump 1.5HP",
                            Price = 3800m,
                            ProductCode = "PUMP-1.5HP",
                            ProductType = "Product",
                            Quantity = 0
                        },
                        new
                        {
                            Id = 9,
                            Category = "Mechanical",
                            CreatedAt = new DateTime(2026, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Workshop compressor",
                            ImageUrl = "/images/products/compressor1.png",
                            IsApproved = true,
                            IsUserSubmitted = false,
                            Name = "Air Compressor 50L",
                            Price = 5200m,
                            ProductCode = "COMP-50L",
                            ProductType = "Product",
                            Quantity = 0
                        },
                        new
                        {
                            Id = 10,
                            Category = "ICT",
                            CreatedAt = new DateTime(2026, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Business router",
                            ImageUrl = "/images/products/router1.webp",
                            IsApproved = true,
                            IsUserSubmitted = false,
                            Name = "Networking Router Pro",
                            Price = 2800m,
                            ProductCode = "ROUTER-PRO",
                            ProductType = "Product",
                            Quantity = 0
                        },
                        new
                        {
                            Id = 11,
                            Category = "ICT",
                            CreatedAt = new DateTime(2026, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "ICT service",
                            ImageUrl = "/images/services/it.jpg",
                            IsApproved = true,
                            IsUserSubmitted = false,
                            Name = "Laptop Repair Service",
                            Price = 800m,
                            ProductCode = "LAPTOP-REPAIR",
                            ProductType = "Service",
                            Quantity = 0
                        },
                        new
                        {
                            Id = 12,
                            Category = "Software",
                            CreatedAt = new DateTime(2026, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "System",
                            ImageUrl = "/images/products/village-banking.jpg",
                            IsApproved = true,
                            IsUserSubmitted = false,
                            Name = "Village Banking Suite",
                            Price = 25000m,
                            ProductCode = "VILLAGE-BANKING",
                            ProductType = "Product",
                            Quantity = 0
                        },
                        new
                        {
                            Id = 13,
                            Category = "Software",
                            CreatedAt = new DateTime(2026, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Gov system",
                            ImageUrl = "/images/products/complaint.jpg",
                            IsApproved = true,
                            IsUserSubmitted = false,
                            Name = "Complaint System",
                            Price = 30000m,
                            ProductCode = "COMPLAINT-SYS",
                            ProductType = "Product",
                            Quantity = 0
                        },
                        new
                        {
                            Id = 14,
                            Category = "Web",
                            CreatedAt = new DateTime(2026, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Event system",
                            ImageUrl = "/images/products/wedding.jpg",
                            IsApproved = true,
                            IsUserSubmitted = false,
                            Name = "Wedding Platform",
                            Price = 5000m,
                            ProductCode = "WEDDING-APP",
                            ProductType = "Product",
                            Quantity = 0
                        },
                        new
                        {
                            Id = 15,
                            Category = "Service",
                            CreatedAt = new DateTime(2026, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Software service",
                            ImageUrl = "/images/services/app-dev.jpg",
                            IsApproved = true,
                            IsUserSubmitted = false,
                            Name = "App Development",
                            Price = 15000m,
                            ProductCode = "APP-DEV",
                            ProductType = "Service",
                            Quantity = 0
                        },
                        new
                        {
                            Id = 16,
                            Category = "Service",
                            CreatedAt = new DateTime(2026, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Hosting service",
                            ImageUrl = "/images/services/cloud.jpg",
                            IsApproved = true,
                            IsUserSubmitted = false,
                            Name = "Cloud Hosting",
                            Price = 2000m,
                            ProductCode = "CLOUD-HOST",
                            ProductType = "Service",
                            Quantity = 0
                        },
                        new
                        {
                            Id = 17,
                            Category = "Service",
                            CreatedAt = new DateTime(2026, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Upgrade service",
                            ImageUrl = "/images/services/upgrade.jpg",
                            IsApproved = true,
                            IsUserSubmitted = false,
                            Name = "System Upgrades",
                            Price = 10000m,
                            ProductCode = "SYS-UPGRADE",
                            ProductType = "Service",
                            Quantity = 0
                        },
                        new
                        {
                            Id = 18,
                            Category = "Service",
                            CreatedAt = new DateTime(2026, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Support service",
                            ImageUrl = "/images/services/it.jpg",
                            IsApproved = true,
                            IsUserSubmitted = false,
                            Name = "IT Maintenance",
                            Price = 5000m,
                            ProductCode = "IT-MAINT",
                            ProductType = "Service",
                            Quantity = 0
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("YellowphaseWebsite.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("YellowphaseWebsite.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YellowphaseWebsite.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("YellowphaseWebsite.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YellowphaseWebsite.Models.Order", b =>
                {
                    b.HasOne("YellowphaseWebsite.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("YellowphaseWebsite.Models.Product", b =>
                {
                    b.HasOne("YellowphaseWebsite.Models.ApplicationUser", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId");

                    b.Navigation("Seller");
                });
#pragma warning restore 612, 618
        }
    }
}
